service:
  name: ${env:SERVICE_NAME}-apigw

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

resources:
  Resources:
    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: MainApiGateway

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${env:STAGE_ENV}
  role: ${env:LAMBDA_ROLE}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}
  apiGateway:
    restApiId:
      Ref: MainApiGateway
    restApiResources:
      Fn::GetAtt:
        - MainApiGateway
        - RootResourceId

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
