version: 0.2
phases:
  install:
    commands:
      - npm install -g serverless@1.35.1
  build:
    commands:
      - cd ./api-gateway
      - npm install
      - serverless deploy
  post_build:
    commands:
      - touch dummy.zip
artifacts:
  files:
    - dummy.zip