service:
  name: ${env:SERVICE_NAME}-service-goodbye

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  stage: ${env:STAGE_ENV}
  role: ${env:LAMBDA_ROLE}
  deploymentBucket:
    name: ${env:DEPLOY_BUCKET}
  apiGateway:
    restApiId: ${env:REST_API_ID}
    restApiRootResourceId: ${env:REST_API_ROOT_RESOURCE_ID}

functions:
  goodbye:
    handler: handler.goodbye
    events:
      - http:
          method: get
          path: goodbye
          authorizer:
            type: CUSTOM
            authorizerId: ${env:AUTHORIZER_ID}
